title: Anustup Bhaumik
description: A curious learner
theme: jekyll-theme-minimal

# Sidebar Quick Links
#github_username: AnustupBhaumik
#linkedin_username: anustup-bhaumik


# Navigation Links across separate pages
header_pages:
  - index.md
  - projects.md
  - blog.md
  - contact.md

permalink: /blog/:title/
