title: Anustup Bhaumik
description: A curious learner
remote_theme: pages-themes/midnight@v0.2.0

# Sidebar Quick Links
github_username: AnustupBhaumik
linkedin_username: anustup-bhaumik


# Navigation Links across separate pages
header_pages:
  - index.md
  - projects.md
  - blog.md
  - contact.md

permalink: /blog/:title/
